# Generated by Django 3.2.16 on 2023-04-04 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20230404_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes_by',
            field=models.ManyToManyField(blank=True, related_name='tweet_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='views_by',
            field=models.ManyToManyField(blank=True, related_name='tweet_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
