# Generated by Django 3.2.16 on 2023-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230404_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='views_by',
        ),
        migrations.AddField(
            model_name='tweet',
            name='views_by',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='tweet view by'),
        ),
    ]
