# Generated by Django 3.2.16 on 2023-03-11 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profil.utils
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profile name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=profil.utils.user_diresctory, verbose_name='Picture')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to=profil.utils.user_diresctory, verbose_name='Cover picture')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Say more about you.')),
                ('about', tinymce.models.HTMLField()),
                ('location', models.CharField(max_length=50, verbose_name='Your current location')),
                ('career', models.CharField(max_length=50, verbose_name='Your career')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='for_profil',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='for_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profil.profile'),
        ),
    ]
