# Generated by Django 3.2.16 on 2023-03-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20230311_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
